modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory
[[mods]] #mandatory
modId="infstore" #mandatory
version="0.1" #mandatory
displayName="Infinite storage" #mandatory
description='''
THE infinite storage mod
'''